name: online_events
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.0.0
  carousel_slider: ^4.0.0
  intl: ^0.18.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.8.0
  sensors_plus: ^4.0.1
  network_info_plus: ^4.1.0
  collection: ^1.17.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  webview_flutter: ^4.4.2
  appwrite: ^11.0.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/models/
    - assets/svg/
    - lib/.env
    - assets/bits/
    - html/

  fonts:
      - family: SourceSans
        fonts:
          - asset: assets/fonts/Poppins-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
