name: online
description: Online App
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.0.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
  sensors_plus: ^6.0.1
  network_info_plus: ^6.0.1
  collection: ^1.17.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  webview_flutter: ^4.4.2
  appwrite: ^13.0.0
  image_cropper: ^8.0.2
  path_provider: ^2.0.9
  qr_flutter: ^4.1.0
  flutter_inappwebview: ^6.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  flutter_markdown: ^0.7.3+2
  url_launcher: ^6.2.4
  url_launcher_ios: ^6.3.1
  flutter_fortune_wheel: ^1.3.1
  app_tracking_transparency: ^2.0.4
  auth0_flutter: ^1.5.0
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  swipeable_page_route: ^0.4.2
  native_ios_dialog: ^0.2.1
  accordion: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/lucide/
    - assets/images/
    - assets/svg/
    - html/
    - lib/.env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
