name: online
description: Online App
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.0.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
  sensors_plus: ^4.0.1
  network_info_plus: ^4.1.0
  collection: ^1.17.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  webview_flutter: ^4.4.2
  appwrite: ^11.0.1
  image_cropper: ^5.0.1
  path_provider: ^2.0.9
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_firebase_recaptcha: ^1.0.2
  flutter_inappwebview: ^5.8.0
  overlay_support: ^2.1.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  android_intent_plus: ^4.0.3
  flutter_markdown: ^0.6.19
  url_launcher: ^6.2.4
  flutter_fortune_wheel: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/bits/
    - assets/icons/
    - assets/images/
    - assets/models/
    - assets/svg/
    - lib/.env
    - html/

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
