// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:358865722949:web:5ad88b438ae885cfa84d2c',
    messagingSenderId: '358865722949',
    projectId: 'online-appen',
    authDomain: 'online-appen.firebaseapp.com',
    storageBucket: 'online-appen.appspot.com',
    measurementId: 'G-7R51FZW12X',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:358865722949:android:bbfb0a03f93a5690a84d2c',
    messagingSenderId: '358865722949',
    projectId: 'online-appen',
    storageBucket: 'online-appen.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:358865722949:ios:d590b9206894df90a84d2c',
    messagingSenderId: '358865722949',
    projectId: 'online-appen',
    storageBucket: 'online-appen.appspot.com',
    iosBundleId: 'ntnu.online.app',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MAC_API_KEY']!,
    appId: '1:358865722949:ios:f52a45b9504781a3a84d2c',
    messagingSenderId: '358865722949',
    projectId: 'online-appen',
    storageBucket: 'online-appen.appspot.com',
    iosBundleId: 'com.example.onlineEvents.RunnerTests',
  );
}
