final questions = [
  'Hvem er den største kokken?',
  'Hvem sin kode fungerer alltid uansett hvor dårlig den ser ut?',
  'Hvem er best venn med GPT?',
  'Hvem er det som alltid møter opp på forelesning?',
  'Hvem stikker alltid hjem etter forelesning?',
  'Hvem har størst sannsynlighet til å sovne på vors?',
  'Hvem spør alltid om å queue på vors?',
  'Hvem trenger ikke vise medlemskortet på Samf?',
  'Hvem er med på alt?',
  'Hvem stjeler mest fra kiosken?',
  'Største boomer?',
  'Største Gen Z?',
  'Hvem har bedreppene rundt lillefingeren?',
  'Hvem får alltid tak i ekstra bonger?',
  'Hvem konter mest?',
  'Hvem er mest syk?',
  'Hvem hoster flest vors? Ta en slurk for hosten som må deale med dere!',
  'Hvem er den største bodega-krigeren?',
  'Hvem hadde brukt JavaFX uironisk?',
  'Hvem er mest kansellerbar? Pass på litt ekstra etter drikkinga du...',
  'Hvem ser mest ut som de snuser?',
  'Hvem er på Debug\'s top 10 most wanted?',
  'Hvem kommer alltid en time etter de sa de var på vei?',
  'Hvem ligger alltid bakpå øvinger?',
  'Hvem ville du helst hatt med på en øde øy?',
  'Hvem er den største karaokestjerna?',
  'Hvem er kronisk hang? På 2-dagers allerede, eller?',
  'Hvem gir deg høyest blodtrykk?',
  'Hvem insjer mest (realfags)kjeller?',
  'Hvem ville du helst ikke vert fanga i en heis med?',
  'Hvem er medlem av kontorsofaklubben?',
  'Hvem er best i Smash?',
  'Hvem er best i Mario Kart?',
  'Hvem ignorerer smashpausen?',
  'Hvem tar de lengste \'pausene\'?',
  'Hvem ender alltid opp på Heidi\'s?',
  'Hvem drar alltid på Cavasøndag?',
  'Hvem er mest keen på å være fadder?',
  'Hvem er din partner-in-crime for øvinger og gruppearbeid?',
  'Hvem tilbringer mest tid på kontoret?',
  'Hvem forsvinner først på Samf?',
  'Hvem har en uforklarlig evne til å alltid finne veien hjem, uansett hvor borte de er?',
  'Hvem får ikke kjøpe drikke i baren?',
  'Hvem detter først i bakken i Åre?',
  'Hvem skal \'stå på ski\' i Åre?',
  'Hvem blir kastet ut først fra Immball?',
  'Hvem må fortsatt vise leg på Vinmonopolet?',
  'Hvem kommer senest på vors?',
  'Hvem er dårligst i beerpong?',
  'Hvem har fått flest prikker?',
  'Hvem skir på isen på vei til Bygget?',
  'Hvem er mest sannsynlig til å ende opp på Red Wines Wall of Shame?',
  'Hvem brenner flest Hiroshima-shots på Circus?',
  'Hvem spør mest \'for en venn\' i Online Slacken?',
  'Hvem er på største A4-bonna?',
  'Hvem er den sterkeste A4-krigeren?',
  'Hvem finner du alltid i Realfagkantina?',
  'Hvem er litt for vennlig med abakuler?',
  'Hvem har de mest kreative rostene?',
  'Hvem har de dårligste comebacksa?',
  'Hvem sitt storstipend forsvinner på mystisk vis hver semesterstart?',
  'Hvem starter en OnlyFans hvis de stryker Algdat en gang til!',
  'Hvem kunne startet den neste store crypto scammen?',
  'Hvem hadde brukt «Passord123» som passord?',
  'Hvem sitt rom ser ut som et diskotek på grunn av alt i RGB?',
  'Hvem ser Wolf of Wallstreet hver dag som \'Pensum\' i sigma grindset?',
  'Hvem er et academic weapon?',
  'Hvem er et academic victim?',
  'Hvem syns fortsatt at dette tallet er morsomt? Voks opp... Ta 3 straffeslurker',
  'Hvem er flinkest til å diskutere? Diskuter deg til en shot!!',
  'Hvem kunne kysset noen for en drink på byen? Hva med noen i rommet? 😉',
  'Hvem starter den neste store interessegruppen?',
  'Hvem spammer emojis som en 14 år gammel jente?',
  'Hvem er en gud i tetris battle fra videregående?',
  'Hvem kunne vært en jock i en American High School film?',
  'Hvem kunne vært lead Cheerleader i en American High School film?',
  'Hvem bruker fortsatt kalkulatoren sin til å skrive 5318008?',
  'Hvem preacher fargene til NTNUI?',
  'Hvem planlegger hybelen sin i Sims?',
  'Hvem bruker alt i light mode?',
  'Hvem har lengst streak på Duolingo?',
  'Hvem har mest hvit monster i blodet?',
  'Hvem får grønnsakene sine fra Mama Nudler?',
  'Hvem lager best memes under genfors?',
  'Hvem gjør alltid noe meme-verdig under genfors?',
  'Hvem klager på at eksamen gikk dritt, men alltid får bra karakter?',
  'Hvem svarer på spørsmål på StackOverflow?',
  'Hvem bruker Reddit AITA til å stille spørsmål om livet sitt?',
  'Hvem har Samfundets BESTE sjekkereplikk? Sjekk opp personen til venstre da vel 😉',
  'Hvem har den VERSTE? Kanskje du kan få noen tips fra gruppa?',
  'Hvem er mest flat-earther?',
  'Hvem legger alltid ut for drikke på Samf når du har for lite på brukskonto?',
  'Hvem har alltid en (ikke nødvendigvis god) plan på byen?',
  'Hvem spiller mest League of Legends?',
  'Hvem burde virkelig få seg litt frisk luft og røre gress?',
  'Hvem sitter mer på Netflix enn?',
  'Hvem er den største romantikeren? #rizz',
  'Hvem sover aldri i sin egen seng etter en kveld på byen?',
  'Hvem er ditt A4 gang-crush?',
  'Hvem løper vekk fra purken? (Hvis de blir tatt)',
].reversed.toList();
