name: Build iOS Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - run: flutter pub get
      - run: flutter build ipa --release

      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa 
