name: Build and Test

on:
  push:
    branches: [ main, production ]   # Adjust trigger branches as needed
  pull_request:
    branches: [ main, production ] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # You can use macOS for iOS builds too

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.x'  # Specify your Flutter version

      - run: flutter pub get 
      - run: flutter build apk # Build an Android APK (or 'flutter build ipa' for iOS)
