name: Build and Test

on:
  push:
    branches: [ main, production ] 
  pull_request:
    branches: [ main, production ] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    steps:
      - name: Decode key.properties and local.properties
        env:
          ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }} 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo $KEY_PROPERTIES | base64 --decode > key.properties && echo $LOCAL_PROPERTIES | base64 --decode > local.properties
      
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'  

      - name: Cache Flutter dependencies
        uses: actions/cache@v3

      - uses: actions/setup-java@v3 
        with:
          distribution: 'temurin' 
          java-version: '17' 

      - run: flutter pub get 
      - run: flutter build appbundle
